Ext.define('XBSF.model.GraduateError',{
    extend:'Ext.data.Model',
    fields:[
        {name:'xn',type:'string'},
        {name:'xh',type:'string'},
        {name:'xm',type:'string'},
        {name:'yx',type:'string'},
        {name:'zy',type:'string'},
        {name:'bj',type:'string'},
        {name:'cw',type:'string'}
    ]
});