Ext.define('XBSF.model.SwxxError',{
    extend:'Ext.data.Model',
    fields:[
        {name:'xh',type:'string'},
        {name:'swbm',type:'string'},
        {name:'sw',type:'string'},
        {name:'swblzt',type:'string'},
        {name:'cw',type:'string'}
    ]
});